# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xatPrivat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fxatPrivat.proto\"1\n\x0eMessageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"\x1f\n\x0cMessageReply\x12\x0f\n\x07message\x18\x01 \x01(\t2:\n\x07Greeter\x12/\n\x0bSendMessage\x12\x0f.MessageRequest\x1a\r.MessageReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xatPrivat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEREQUEST']._serialized_start=19
  _globals['_MESSAGEREQUEST']._serialized_end=68
  _globals['_MESSAGEREPLY']._serialized_start=70
  _globals['_MESSAGEREPLY']._serialized_end=101
  _globals['_GREETER']._serialized_start=103
  _globals['_GREETER']._serialized_end=161
# @@protoc_insertion_point(module_scope)
