# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xatPrivat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fxatPrivat.proto\x12\ntu_paquete\"1\n\x0eMessageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"\x1f\n\x0cMessageReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x8d\x01\n\x07Greeter\x12\x43\n\x0bSendMessage\x12\x1a.tu_paquete.MessageRequest\x1a\x18.tu_paquete.MessageReply\x12=\n\x0eReceiveMessage\x12\x11.tu_paquete.Empty\x1a\x18.tu_paquete.MessageReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xatPrivat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEREQUEST']._serialized_start=31
  _globals['_MESSAGEREQUEST']._serialized_end=80
  _globals['_MESSAGEREPLY']._serialized_start=82
  _globals['_MESSAGEREPLY']._serialized_end=113
  _globals['_EMPTY']._serialized_start=115
  _globals['_EMPTY']._serialized_end=122
  _globals['_GREETER']._serialized_start=125
  _globals['_GREETER']._serialized_end=266
# @@protoc_insertion_point(module_scope)
