# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xatPrivat/xatPrivat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19xatPrivat/xatPrivat.proto\"@\n\x0eMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"/\n\x0fMessageResponse\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t29\n\x03Xat\x12\x32\n\x0bSendMessage\x12\x0f.MessageRequest\x1a\x10.MessageResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xatPrivat.xatPrivat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEREQUEST']._serialized_start=29
  _globals['_MESSAGEREQUEST']._serialized_end=93
  _globals['_MESSAGERESPONSE']._serialized_start=95
  _globals['_MESSAGERESPONSE']._serialized_end=142
  _globals['_XAT']._serialized_start=144
  _globals['_XAT']._serialized_end=201
# @@protoc_insertion_point(module_scope)
